spring :
  datasource :
    url : jdbc://mysql:127.0.0.1:3306/spring-boot-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : 123456